### ISSUE TITLE
Dockerfile Listens on wrong port

### ISSUE THREAD

**Issue by aultl** [budgetzero/budgetzero#24]
Dockerfile contains EXPOSE 80 command; however, the default nginx.conf file is configured to listen on port 8080. This causes ingress controllers to fail as the published port is different than the application port.

**Comment by simokarpin** [comment]
Seems like fixed issue? -> 
https://github.com/budgetzero/budgetzero/commit/8a84f3e062214647a89339ace22ca71dac01b55e

**Comment by stefanjf** [comment]
Updated in 8a84f3e
