### ISSUE TITLE
import csv does not work

### ISSUE THREAD

**Issue by TheNomad11** [budgetzero/budgetzero#88]
I installed budgetzero via docker on a VPS (Ubuntu 20) and everything looks fine. I can add transactions but importing csv from my bank failed. I mapped the correct fields, it showed up fine in the preview, then I pressed "import transactions", it said 23 transactions imported, but nothing showed up, everything empty, zero transactions available

**Comment by trisell** [comment]
I pushed a fix up that appears to fix this issue. Seems that there was a refactor from updateTransaction to createOrUpdateTransaction.
