### ISSUE TITLE
CI Workflow using `npm install`

### ISSUE THREAD

**Issue by MalikKillian** [budgetzero/budgetzero#98]
I noticed that the `unit_test` job is installing packages by running `npm i`. This isn't good practice for a CICD setup. You already have a `package-lock.json` so you should be using `npm ci` in automated workflows.

Personally, I've had many issues with sudden bugs or other behaviors that couldn't be reproduced because of differences caused by `npm install` running at different times. During development you just need to get into the habit of running `npm i` at the start of a new branch.

**Comment by stefanjf** [comment]
Thanks for the tip! 👍
